### ISSUE TITLE
Token not shown in original sentence

### ISSUE THREAD

**Issue by JueXiuHuang** [luyaojie/Text2Event#12]
Hi,
I tried to use Text2Event in Chinese corpus, and your model have great performance in my task.

However, I got some weird result when I try to predict the event in the sentence.
The weird result shown as below:
> Original sentence:
> 上 回 我 們 說 到 曹 操 帶 了 百 萬 大 軍 ， 乘 一 千 艘 戰 船 去 攻 打 東 吳 。
> Result:
> {'roles': [('Attack', 'Attacker', '曹 操'), ('Attack', 'Target', '西 吳')], 'type': 'Attack', 'trigger': '攻 打'}

Most result is correct, but word "東 吳" was turn into "西 吳".

Does this result happen in English corpus? And how can I fix it?

**Comment by luyaojie** [comment]
Hi,

The English model also has this problem. For instance, the raw sentence has `dad`, but the generated result is `father`.

I have tried to fix this problem in two ways:

1. Constrained decoding in the raw paper: this way constrains the extracted span is generated from text.
It requires the tokenized token sequence should be consistent with the constrained rules. 
(Because some tokenizers will generate some extra spaces.)
details see below functions.
https://github.com/luyaojie/Text2Event/blob/bfa818c58f1856a2bce194e58b53995a22be0f72/extraction/extract_constraint.py#L38
https://github.com/luyaojie/Text2Event/blob/bfa818c58f1856a2bce194e58b53995a22be0f72/extraction/extract_constraint.py#L186

2. Replace the generated string with some extract rules. For example, if `西吳` is not found in the raw text, you can drop the extracted string or replace the extracted result based on the in-text char `吳`.
In my practice, this method is used to fix \<unk\> token in the generated sequence.
